// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdj5kIF_suezo1DnkkB70JVeLYCzdM_KE',
    appId: '1:676175984214:web:6cd76be8844930d7aeadf7',
    messagingSenderId: '676175984214',
    projectId: 'flutter-sample-instagram',
    authDomain: 'flutter-sample-instagram.firebaseapp.com',
    storageBucket: 'flutter-sample-instagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYOcBMYprPnEerqiJC71JU5c5skizlh8',
    appId: '1:676175984214:android:7091afa9ee2420f2aeadf7',
    messagingSenderId: '676175984214',
    projectId: 'flutter-sample-instagram',
    storageBucket: 'flutter-sample-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7jmm_3vBMYC-OWNglb9oVlnEtcMhegdo',
    appId: '1:676175984214:ios:9eb22e0895e57746aeadf7',
    messagingSenderId: '676175984214',
    projectId: 'flutter-sample-instagram',
    storageBucket: 'flutter-sample-instagram.appspot.com',
    iosClientId: '676175984214-g78ef0s1dvtgktku0l4h6q4v6gssrndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSampleInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7jmm_3vBMYC-OWNglb9oVlnEtcMhegdo',
    appId: '1:676175984214:ios:9eb22e0895e57746aeadf7',
    messagingSenderId: '676175984214',
    projectId: 'flutter-sample-instagram',
    storageBucket: 'flutter-sample-instagram.appspot.com',
    iosClientId: '676175984214-g78ef0s1dvtgktku0l4h6q4v6gssrndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSampleInstagram',
  );
}
